<a href="https://colab.research.google.com/github/nadgir-praveen/data-science-lab/blob/main/assignments/M1_AST_08_Tensor_Operations_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Assignment 8: Tensor Operations

## Learning Objectives

At the end of the experiment, you will be able to
* understand Tensors and their application
* define/form Tensors
* perform different operations of Tensor using NumPy and Tensorflow library

## Information

**Tensors**: Tensor, in relation to machine learning, is a generalization of scalars, vectors, and matrices as seen in the table below.

![img](https://cdn.iisc.talentsprint.com/CDS/Images/tensors.JPG)

* From the above explanation, you might have understood that Tensor operations are nothing but matrix operations.

**Tensorflow**:
We are introducing Tensorflow here, a widely used library for Machine Learning, specifically deep learning. Tensorflow's name is directly derived from its core framework: Tensor and all the computations carried out involve Tensor and its operations.TensorFlow was developed by the Google Brain team and first released under the Apache License 2.0 in 2015.
* In the following sections, we will see few commonly used operations of Tensor using both NumPy and TensorFlow Library.

### Setup Steps:

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2301978" #@param {type:"string"}

In [ ]:
#@title Please enter your password (your registered phone number) to continue: { run: "auto", display-mode: "form" }
password = "9844001418" #@param {type:"string"}

In [ ]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "M1_AST_08_Tensor_Operations_C" #name of the notebook

def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer" : Answer, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://cds-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer():
  try:
    if not Answer:
      raise NameError
    else:
      return Answer
  except NameError:
    print ("Please answer Question")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


#### Importing Required Packages

In [ ]:
import numpy as np
import tensorflow as tf

### Defining and slicing a 2D/1D-Tensor

#### NumPy

In [ ]:
a=np.array([[1,2],[2,3],[6,7]])             # Defining a 2D array in Numpy
print(a)                                    # printing the array
print('shape = ',a.shape)                   # '.shape' method gives the number of rows and columns in the form of a tuple
print('dimension = ',a.ndim)                # It gives dimension of the array
print('size =',np.size(a))                  # size always gives total number of elements in any array
print('lengths = ',len(a))                  # In 2D it gives the number of rows in an array
print('data structure type : ',type(a))     # It gives the type of data structure
a.dtype                                     # it gives type of data stored in array

[[1 2]
 [2 3]
 [6 7]]
shape =  (3, 2)
dimension =  2
size = 6
lengths =  3
data structure type :  <class 'numpy.ndarray'>


dtype('int64')

##### Slicing: We are going to define a 2D Matrix as given in the image below and apply the slicing operations.

![2Dimg](https://cdn.iisc.talentsprint.com/CDS/Images/2D_array_slicing.JPG)

In [ ]:
## Creating a 2D array
a2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
a2d

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [ ]:
# slicing the 2nd index row
a2d[2]

array([ 7,  8,  9, 10])

In [ ]:
# zeroth row
a2d[0]

array([1, 2, 3, 4])

In [ ]:
# The first value before coma is for row index and the second value after coma is for column index.
a2d[1,3]

7

In [ ]:
# This can also used.
a2d[1][3]

7

In [ ]:
# Using negative index
a2d[-2,-3]

5

In [ ]:
# from the very beginning to -2 indexed row (i.e -3 and -2 indexed row) and -3,-4 indexed columns are sliced
a2d[:-1,:-2]

array([[1, 2],
       [4, 5]])

In [ ]:
# from the very beginning to 1 indexed row, i.e 0 and 1 index row sliced. 2 is not included.
a2d[:2]

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
# ( 0 ,1 ) indexed rows and 2 to last indexed columns are sliced.
a2d[:2, 2:]

array([[3, 4],
       [6, 7]])

In [ ]:
# 1 indexed row and (0,1) indexed columns are sliced .
a2d[1, :2]

array([4, 5])

In [ ]:
# Explain yourself?
a2d[:2, 2]

array([3, 6])

In [ ]:
# All rows and 0 column ( from the very beginning, but 1 not included i.e. zeroth column ) sliced.
a2d[:, :1]

array([[1],
       [4],
       [7]])

In [ ]:
print('Initial Matrix = ',a2d)
# This is an assignment operation, a2d  itself gets changed.
a2d[:2, 1:] = 0
print('Matrix after above assigned operations = ',a2d)

Initial Matrix =  [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
Matrix after above assigned operations =  [[ 1  0  0  0]
 [ 4  0  0  0]
 [ 7  8  9 10]]


#### TensorFlow
**tf.Variable**: There are multiple ways of defining/forming a Tensor in Tensorflow, tf.Variable is one of those. A tf.Variable represents a tensor whose value can be changed by running operations on it. Specific operations allow you to read and modify the values of this tensor. Higher-level libraries like tf.keras use tf.Variable to store model parameters that keep changing/updating with subsequent learning steps.

**tf.Constant**: This is another way of creating a Tensor but the tensor made through this cannot be updated but can be called multiple times with only 1 copy in the memory.

In [ ]:
a_tf = tf.Variable([[1,2],[2,3],[6,7]])
print(a_tf)
print("Shape of the input tensor is", tf.shape(a_tf)) # Returns a tensor containing the shape of the input tensor
print("Rank of the input tensor is", tf.rank(a_tf)) # Returns the rank of a tensor
# print(a_tf.ndim) -->  This operation is not valid for tf.variable object.
print("Size of the input tensor is", tf.size(a_tf)) # Returns the size of a tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [6, 7]], dtype=int32)>
Shape of the input tensor is tf.Tensor([3 2], shape=(2,), dtype=int32)
Rank of the input tensor is tf.Tensor(2, shape=(), dtype=int32)
Size of the input tensor is tf.Tensor(6, shape=(), dtype=int32)


##### Slicing: Similar to Numpy array slicing.

In [ ]:
a_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 7], dtype=int32)>

#### Note the difference between 1D tensor, 2D row tensor, and 2D column tensor, explained with an example below.

##### NumPy

In [ ]:
# This is a 1D tensor
V1 = np.array([1,2,3])
print(V1,'\n')
print(V1.shape)

[1 2 3] 

(3,)


In [ ]:
# This is a 2D tensor having 1 row and 3 columns, i.e. 2D row tensor as it contains only one row.
V2 = np.array([[1,2,3]])
print(V2,'\n')
print(V2.shape)

[[1 2 3]] 

(1, 3)


In [ ]:
# This is a 2D tensor having 3 rows and 1 column, ie. a 2D column tensor as it contains only one column.
V3 = np.array([[1],[2],[3]])
print(V3,'\n')
print(V3.shape)

[[1]
 [2]
 [3]] 

(3, 1)


##### TensorFlow

In [ ]:
V1_tf = tf.Variable([1,2,3])
print(V1_tf)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [ ]:
V2_tf = tf.Variable([[1,2,3]])
print(V2_tf)

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>


In [ ]:
V3_tf = tf.Variable([[1],[2],[3]])
print(V3_tf)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>


### Transpose
The new matrix obtained by interchanging the rows and columns of the original matrix is referred to as the transpose of the matrix.

#### NumPy

In [ ]:
print(a2d,'\n')
print(a2d.T)

[[ 1  0  0  0]
 [ 4  0  0  0]
 [ 7  8  9 10]] 

[[ 1  4  7]
 [ 0  0  8]
 [ 0  0  9]
 [ 0  0 10]]


#### TensorFlow

In [ ]:
# Creating a 2D tensor
a2d_tf = tf.Variable([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(a2d_tf)
tf.transpose(a2d_tf)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]], dtype=int32)>


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]], dtype=int32)>

### Scalar Addition and Multiplication
Addition or Multiplication of any higher-order tensor with a scalar quantity(zero-order tensor).

#### NumPy

In [ ]:
print(a)
a+2 # 2 is added to each element of the initial matrix a.

[[1 2]
 [2 3]
 [6 7]]


array([[3, 4],
       [4, 5],
       [8, 9]])

In [ ]:
a*2 # Each element of the initial matrix is multiplied by 2.

array([[ 2,  4],
       [ 4,  6],
       [12, 14]])

#### TensorFlow

In [ ]:
print(a_tf)
tf.add(a_tf,2)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [6, 7]], dtype=int32)>


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 5],
       [8, 9]], dtype=int32)>

In [ ]:
tf.multiply(a_tf,2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 4,  6],
       [12, 14]], dtype=int32)>

### Addition and Subtraction between tensors
When the shape of the tensors is same, element-wise addition and subtraction can be carried out

#### NumPy

In [ ]:
b = np.array([[1,2],[2,3]])
c = np.array([[3,4],[5,6]])
print('b = ','\n',b,'\n','c = ','\n',c)

b =  
 [[1 2]
 [2 3]] 
 c =  
 [[3 4]
 [5 6]]


In [ ]:
print(b+c,'\n')
print(b-c)

[[4 6]
 [7 9]] 

[[-2 -2]
 [-3 -3]]


#### TensorFlow

In [ ]:
b_tf = tf.Variable([[1,2],[2,3]])
c_tf = tf.Variable([[3,4],[5,6]])
print(b_tf,'\n',c_tf)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)> 
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>


In [ ]:
tf.add(b_tf,c_tf) # Addition

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 9]], dtype=int32)>

In [ ]:
tf.subtract(b_tf,c_tf) # subtraction

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -2],
       [-3, -3]], dtype=int32)>

### Concept of Broadcasting

Understand by going through the examples given below.

#### NumPy

To know more about broadcasting click [here](https://numpy.org/devdocs/user/theory.broadcasting.html).

In [ ]:
M1 = np.array([[1,2,3],[4,5,6]])
print(M1)
M1.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
M2 = np.array([[8],[9]])
print(M2)
M2.shape

[[8]
 [9]]


(2, 1)

Mathematically M1 and M2 cannot be added as the shape doesn't match, but in NumPy, they can be added. M2 has the same number of rows as that of M1. Its column gets replicated so that its shape becomes equal to M1, and then, both are added. This process of replication is broadcasting. M2 gets broadcasted in the direction of the column of M1. We will see the result after replication and sum operation. Broadcasted M2 is not visible, it is a hidden step. See the result below:

In [ ]:
M1+M2

array([[ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
# Making another array M3
M3 = np.array([[10,20,30]])
print(M3)
M3.shape

[[10 20 30]]


(1, 3)

Mathematically M1 and M3 can not be added as the shape doesn't match, but in NumPy, they can be added. M3 has the same number of columns as that of M1. Its rows get replicated so that its shape becomes equal to M1, and then, both are added. This process of replication is broadcasting. M3 gets broadcasted in the direction of the rows of M1. We will see the result after replication and sum operation. Broadcasted M3 is not visible, it is a hidden step. See the result below:

In [ ]:
M1+M3

array([[11, 22, 33],
       [14, 25, 36]])

#### TensorFlow
 Similar to NumPy.

In [ ]:
M1_tf = tf.Variable([[1,2,3],[4,5,6]])
print(M1_tf,'\n')
M2_tf = tf.Variable([[8],[9]])
print(M2_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)> 

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[8],
       [9]], dtype=int32)>


In [ ]:
tf.add(M1_tf,M2_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 10, 11],
       [13, 14, 15]], dtype=int32)>

### Hadamard Product or Element-wise Multiplication
If the two Tensors have the same size, operations are carried out elementwise by default.

#### NumPy

In [ ]:
# Using previously defined matrix a by using  Numpy
a

array([[1, 2],
       [2, 3],
       [6, 7]])

In [ ]:
# Defining another matrix b
b = np.array([[2,3],[1,2],[4,5]])
b

array([[2, 3],
       [1, 2],
       [4, 5]])

In [ ]:
# Here the shape of a  and b matches thus default product is Hadamard multiplication. Note: This is not matrix multiplication.
a*b

array([[ 2,  6],
       [ 2,  6],
       [24, 35]])

#### TensorFlow

In [ ]:
a_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [6, 7]], dtype=int32)>

In [ ]:
b_tf = tf.Variable([[2,3],[1,2],[4,5]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 3],
       [1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
a_tf * b_tf # Hadamard Multiplication
# OR tf.multiply(a_tf,b_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  6],
       [ 2,  6],
       [24, 35]], dtype=int32)>

### Matrix Multiplication
* For multiplying matrix a and matrix b, the number of columns of matrix a and the number of rows of matrix b must match.
* Note: Matrix Multiplication is not commutative (i.e.AB != BA)

Matrix multiplication process
![img](https://cdn.iisc.talentsprint.com/CDS/Images/Tensor_matmul.JPG)

#### NumPy

In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1,'\n','Shape = ',a1.shape)
b1 = np.array([[2,1],[3,2],[4,3]])
print(b1,'\n','Shape = ',b1.shape)

[[1 2 3]
 [4 5 6]] 
 Shape =  (2, 3)
[[2 1]
 [3 2]
 [4 3]] 
 Shape =  (3, 2)


In [ ]:
# Matrix multiplication between a1 and b1 is possible as
# the number of columns of matrix a and the number of rows of matrix b are equal.
np.dot(a1,b1) # OR
a1.dot(b1)

array([[20, 14],
       [47, 32]])

#### TensorFlow

In [ ]:
a1_tf = tf.Variable([[1,2,3],[4,5,6]])
print(a1_tf,'\n')
b1_tf = tf.Variable([[2,1],[3,2],[4,3]])
print(b1_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)> 

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 1],
       [3, 2],
       [4, 3]], dtype=int32)>


In [ ]:
tf.linalg.matmul(a1_tf,b1_tf)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [47, 32]], dtype=int32)>

### Tensordot or Tensor Contraction
Tensordot operation is carried out between input arrays based on the respective axes ( passed as an arg.) along which the sum-reductions are intended.
The axes that take part in sum-reduction are removed in the output, and all of the remaining axes from the input arrays are spread out as different axes in the output, keeping the order in which the input arrays are fed.

#### NumPy

Go through the examples given below and visit the reference to comprehend it properly.

To know more tensordot in numpy, refer the [link](https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html)

In [ ]:
# Defining tensors
a1 = np.array([[1,2,3],[2,3,1]])
a2 = np.array([[1,2],[3,4],[2,3]])
print("Tensor1 is: \n ", a1)
print("Tensor2 is: \n", a2)

# Calculating tensordot
r1 = np.tensordot(a1, a2, axes=([0,1])) # Same when axes are passed as -->  axes=([0],[1])  OR   axes=([[0],[1]])
print("Tensordot of these tensors is:\n", r1)
print("Shape : ", r1.shape)

Tensor1 is: 
  [[1 2 3]
 [2 3 1]]
Tensor2 is: 
 [[1 2]
 [3 4]
 [2 3]]
Tensordot of these tensors is:
 [[ 5 11  8]
 [ 8 18 13]
 [ 5 13  9]]
Shape :  (3, 3)


* When a and b are matrices (order 2), the case axes = 1 is equivalent to matrix multiplication.
* When a and b are matrices (order 2), the case axes = [[1], [0]] is equivalent to matrix multiplication.

In [ ]:
r1 = np.tensordot(a1, a2,axes=1)
r1

array([[13, 19],
       [13, 19]])

In [ ]:
r1 = np.tensordot(a1, a2,axes=([1,0]))  # Same when axes are passed as -->  axes=([1],[0])  OR   axes=([[1],[0]])
r1

array([[13, 19],
       [13, 19]])

* When a and b are matrices (order 2), the case axes=0 gives the outer product, a tensor of order 4.

In [ ]:
r1 = np.tensordot(a1, a2,axes=0)       # Outer Product
print("Resulting Tensor : \n", r1)
r1.shape

Resulting Tensor : 
 [[[[ 1  2]
   [ 3  4]
   [ 2  3]]

  [[ 2  4]
   [ 6  8]
   [ 4  6]]

  [[ 3  6]
   [ 9 12]
   [ 6  9]]]


 [[[ 2  4]
   [ 6  8]
   [ 4  6]]

  [[ 3  6]
   [ 9 12]
   [ 6  9]]

  [[ 1  2]
   [ 3  4]
   [ 2  3]]]]


(2, 3, 3, 2)

#### TensorFlow

Similar as NumPy.

To know more about tensordot, refer the [link](https://www.tensorflow.org/api_docs/python/tf/tensordot)

In [ ]:
# Defining tensors
a1_tf = tf.Variable([[1,2,3],[2,3,1]])
a2_tf = tf.Variable([[1,2],[3,4],[2,3]])
print("Tensor1 is: \n ", a1_tf)
print("Tensor2 is: \n", a2_tf)

# Calculating tensordot
r1_tf = tf.tensordot(a1_tf, a2_tf, axes=([0,1]))  # Same when axes are passed as -->  axes=([0],[1])  OR   axes=([[0],[1]])
print("Tensordot of these tensors is:\n", r1_tf)
print("Shape : ", tf.shape(r1_tf))

Tensor1 is: 
  <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 1]], dtype=int32)>
Tensor2 is: 
 <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [2, 3]], dtype=int32)>
Tensordot of these tensors is:
 tf.Tensor(
[[ 5 11  8]
 [ 8 18 13]
 [ 5 13  9]], shape=(3, 3), dtype=int32)
Shape :  tf.Tensor([3 3], shape=(2,), dtype=int32)


In [ ]:
r1_tf = tf.tensordot(a1_tf, a2_tf,axes=0)  # Outer Product
print("Resulting Tensor : \n", r1_tf)
tf.shape(r1_tf)

Resulting Tensor : 
 tf.Tensor(
[[[[ 1  2]
   [ 3  4]
   [ 2  3]]

  [[ 2  4]
   [ 6  8]
   [ 4  6]]

  [[ 3  6]
   [ 9 12]
   [ 6  9]]]


 [[[ 2  4]
   [ 6  8]
   [ 4  6]]

  [[ 3  6]
   [ 9 12]
   [ 6  9]]

  [[ 1  2]
   [ 3  4]
   [ 2  3]]]], shape=(2, 3, 3, 2), dtype=int32)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 3, 2], dtype=int32)>

**Note:** we have illustrated only 2nd order Tensordot operation. For operations on higher-order Tensors visit the reference mentioned above.

### Reduction:
Calculating the sum across all elements of a tensor along with any one or multiple dimensions.

#### NumPy

In [ ]:
a   # Using the matrix/tensor defined above using Numpy

array([[1, 2],
       [2, 3],
       [6, 7]])

In [ ]:
print(a.sum())  # OR
print(np.sum(a))

21
21


* Summation along any one dimension: Here axis=0 means down the rows and axis=1 means along the columns.

In [ ]:
print(a.sum(axis=0))  # OR
print(np.sum(a,axis=0))

[ 9 12]
[ 9 12]


In [ ]:
print(a.sum(axis=1))  # OR
print(np.sum(a,axis=1))

[ 3  5 13]
[ 3  5 13]


**Notice the code below and find the difference between the above and below operations.**

In [ ]:
print(a.sum(axis=1,keepdims=True))  # OR
print(np.sum(a,axis=1,keepdims=True))

[[ 3]
 [ 5]
 [13]]
[[ 3]
 [ 5]
 [13]]


#### TensorFlow

In [ ]:
a_tf    # Using the tensor a_tf defined using Tensorflow

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [6, 7]], dtype=int32)>

In [ ]:
tf.reduce_sum(a_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [ ]:
tf.reduce_sum(a_tf,0)  # down the rows

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 12], dtype=int32)>

In [ ]:
tf.reduce_sum(a_tf,1) # along the columns

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  5, 13], dtype=int32)>

### Tensor/Matrix Determinant & Inversion
* The matrix inversion is only valid for non-singular matrix i.e. matrix with non zero determinants. All columns of the matrix must be linearly independent.
* Inversion is only calculated for the square matrix.

#### NumPy

In [ ]:
X = np.array([[2,3],[5,9]])
X

array([[2, 3],
       [5, 9]])

In [ ]:
np.linalg.det(X) # Determinant calculation

3.0000000000000004

In [ ]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 3.        , -1.        ],
       [-1.66666667,  0.66666667]])

In [ ]:
np.dot(X,X_inv)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.33226763e-15,  1.00000000e+00]])

#### TensorFlow

In [ ]:
# To get inverse, make sure that  tensor has entries as float
X_tf = tf.Variable([[2.,3.],[5.,9.]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [5., 9.]], dtype=float32)>

In [ ]:
# Determinant Calculation
tf.linalg.det(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0000007>

In [ ]:
## To get only the final result, add --> .numpy() at the end as given below. Valid everywhere.
tf.linalg.det(X_tf).numpy()

3.0000007

In [ ]:
X_tf_inv = tf.linalg.inv(X_tf)
X_tf_inv

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.9999993, -0.9999997],
       [-1.6666663,  0.6666665]], dtype=float32)>

In [ ]:
tf.matmul(X_tf,X_tf_inv)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9.9999952e-01, 1.1920929e-07],
       [0.0000000e+00, 1.0000000e+00]], dtype=float32)>

### Higher-order tensor
A colored image consists of three channels of pixels one for Red color, one for Green color, and one for Blue color. Each channel is a 2D matrix. That means, any colored image is represented by a 3-tensor of pixels composed of three 2D matrices stacked one after another and each 2D matrix is called a channel. Say we have an image of 32 megapixels then the shape of the tensor representation of this image is (32,32,3),i.e. three 32X32 matrices are stacked one after another. So this is a tensor of order/rank 3 and it is used for the representation of an image.

![img1](https://cdn.iisc.talentsprint.com/CDS/Images/RGB_Channel.JPG)

Now, say there are 100 such images, then the tensor will be of 4th order and the shape will be (100,32,32,3). So the tensor contains information of 100 images each consists of RGB  channels of 32 by 32 megapixel.
#### NumPy

In [ ]:
# Making a 3 rank/order tensor filled with zeros
np.zeros([3,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Making a 4 rank/order tensor filled with zeros
np.zeros([2,3,2,3])

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

#### TensorFlow

In [ ]:
tf.zeros([3,2,3])

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.zeros([2,3,2,3])

<tf.Tensor: shape=(2, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

### Converting NumPy Tensor into TensorFlow Tensor and vice-versa :

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
x_np = x.numpy()
x_np

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
x_tf = tf.convert_to_tensor(x_np)
x_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

**Comparison** Tensor in NumPy and TensorFlow: We have carried out different operations of Tensor using both NumPy and TensorFlow libraries. In general, the Tensors defined in NumPy are called Nd-Arrays whereas in TensorFlow they are called Tensors.
* Do NumPy arrays differ from Tensors?

There is no difference between Tensors defined through both the libraries apart from the syntactical difference (that we have seen in the above operations) but a Tensor is a more suitable choice if we are going to use GPUs/TPUs as it can reside in accelerators memory. This is the main reasoning behind the application of TensorFlow in deep learning.

To explore more about other operations click [here](https://www.tensorflow.org/guide/tensor).

**Ungraded practice problems**

**Q.1. Two tensors having different shapes**

a) can not be added.

b) can be added mathematically.

c) can be added in NumPy but not in TensorFlow.

d) can be added in both NumPy and TensorFlow.

Answer : d)

**Q.2. Which of the following are not true about matrix multiplication?**

a) Hadamard and Matrix Multiplication are the same operations.

b) Matrix Multiplication can only be done between matrices of the same shape.

c) Element-wise multiplication is the same as that of Matrix Multiplication.

d) Number of columns of the first matrix and number of rows of the second matrix must match for matrix multiplication.

Answer: a),b) and c)

**Q.3. The concept of broadcasting is related to**

a) Inverse of a matrix.

b) Multiplication of matrix.

c) Addition of matrix.

d) Subtraction of Matrix.

Answer: Both c) and d)

### Please answer the questions below to complete the experiment:




In [ ]:
# @title Which of the following may be the shape of a tensor representing 10 color images of size 64 X 64? { run: "auto", form-width: "500px", display-mode: "form" }
Answer = "10 x 3 x 64 x 64" #@param ["","10 x 3 x 64 x 64","10 x 64 x 3", "64 x 10 x 3 x 64", "4 x 64 x 10 x 3"]

In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "No comments" #@param {type:"string"}


In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 1277
Date of submission:  19 Jan 2024
Time of submission:  12:07:54
View your submissions: https://cds-iisc.talentsprint.com/notebook_submissions
